headers/deps: uapi/headers: Create usr/include/uapi symbolic link
We are going to start using using <uapi/**.h> style links in the UAPI
headers, because they are much more lightweight than the full kernel
headers.

But these won't work in sample user-space code:

  In file included from samples/connector/ucon.c:14:
  usr/include/linux/netlink.h:5:10: fatal error: uapi/linux/const.h: No such file or directory

Add a symbolic link from usr/include/uapi to usr/include to redirect
these dependencies.

Signed-off-by: Ingo Molnar <mingo@kernel.org>

backmerge to: 527e3751d2c9: ("sched/headers, uapi/headers: Create usr/include/uapi symbolic link")

Signed-off-by: Ingo Molnar <mingo@kernel.org>